### ISSUE TITLE
missing babel-cli dependency

### ISSUE THREAD

**Issue by laurentpayot** [Akryum/apollo-server-example#1]
After `npm install` and  `npm run dev` I was getting the following:

```
> apollo-server-example@1.0.0 dev /home/laurent/nodejs/apollo-server-example
> nodemon index.js --exec babel-node --presets es2015

[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node index.js --presets es2015`
sh: 1: babel-node: not found
[nodemon] failed to start process, "babel-node" exec not found
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (127)
    at Bus.emit (events.js:163:17)
    at ChildProcess.<anonymous> (/home/laurent/nodejs/apollo-server-example/node_modules/nodemon/lib/monitor/run.js:118:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! apollo-server-example@1.0.0 dev: `nodemon index.js --exec babel-node --presets es2015`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-server-example@1.0.0 dev script 'nodemon index.js --exec babel-node --presets es2015'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon index.js --exec babel-node --presets es2015
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/laurent/nodejs/apollo-server-example/npm-debug.log

```

I had to do `npm install --save-dev babel-cli` to make it work.

**Comment by sseletskyy** [comment]
+1
> I had to do npm install --save-dev babel-cli to make it work.

**Comment by Akryum** [comment]
@sseletskyy Do you still have the issue?

**Comment by sseletskyy** [comment]
@akryum Thank you. No, I don't actually. 
I've just voted for solution, which saved the day ;)

**Comment by Akryum** [comment]
@sseletskyy I mean when you cloned the repo, you still had the error? It was supposed to be fixed in the 20th Oct. commit.

**Comment by sseletskyy** [comment]
@Akryum No, I didn't.

**Comment by tylercrompton** [comment]
Installing `babel-cli` strangely didn't solve this issue for me. :/

**Comment by zersoon** [comment]
npm install -g babel-cli can solve for me.
